project:
  type: book
  output-dir: docs

book:
  title: "Portfolio"
  author: "Erik King-Vargas"
  date: today
  search: true
  page-navigation: true
  repo-url: https://github.com/erikvvargas/ds_projects
  sidebar:
    tools:
      # - icon: share-fill
      #   href: https://erik-king-vargas.carrd.co/
      - icon: linkedin
        href: https://www.linkedin.com/in/erikvvargas/
      - icon: envelope
        href: mailto:erikvvargas@gmail.com
  # links:
  #   - icon: rocket-takeoff
  #   href: https://erik-king-vargas.carrd.co/
  chapters:
    - index.qmd
    - part: "TidyTuesday Projects"
      chapters:
      - week_11-28-2023.qmd
      - week_1-9-2024.qmd
      - week_12-5-2023.qmd
    # - part: "Kaggle Projects"
    #   chapters:
    #   - kaggle_1_spaceship.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    number-sections: true